package Cadastro;

import Gerenciamento.TelaInicial;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Nunweiler
 */
public final class CadastroFornecedor extends javax.swing.JFrame {

    String seta_look = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
    
    
    public CadastroFornecedor() throws ClassNotFoundException {
        initComponents();
        lookandfeel();
        setarIcone();
        setLocationRelativeTo(null);
        lookandfeel();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bo_atualizar = new javax.swing.JButton();
        bo_editar_cliente = new javax.swing.JButton();
        bo_excluir_cliente = new javax.swing.JButton();
        bo_consulta_completa = new javax.swing.JButton();
        la_titulo1_dados_empresa = new javax.swing.JPanel();
        la_titulo = new javax.swing.JLabel();
        se_separador1 = new javax.swing.JSeparator();
        la_nome_titulo_empresa = new javax.swing.JLabel();
        la_nome_fantasia = new javax.swing.JLabel();
        tf_nome_fantasia = new javax.swing.JTextField();
        la_razao_social = new javax.swing.JLabel();
        tf_razao_social = new javax.swing.JTextField();
        la_cnpj = new javax.swing.JLabel();
        tf_cnpj = new javax.swing.JTextField();
        la_inscricao_estadual = new javax.swing.JLabel();
        tf_inscricao_estadual = new javax.swing.JTextField();
        se_separador2 = new javax.swing.JSeparator();
        la_titulo1_dados_endereco_empresa = new javax.swing.JLabel();
        la_rua = new javax.swing.JLabel();
        tf_rua = new javax.swing.JTextField();
        la_numero = new javax.swing.JLabel();
        tf_numero = new javax.swing.JTextField();
        la_bairro = new javax.swing.JLabel();
        tf_bairro = new javax.swing.JTextField();
        la_cidade = new javax.swing.JLabel();
        tf_cidade = new javax.swing.JTextField();
        la_cep = new javax.swing.JLabel();
        tf_cep = new javax.swing.JTextField();
        la_telefone1 = new javax.swing.JLabel();
        tf_telefone1 = new javax.swing.JTextField();
        la_telefone2 = new javax.swing.JLabel();
        tf_telefone2 = new javax.swing.JTextField();
        la_celular = new javax.swing.JLabel();
        tf_celular = new javax.swing.JTextField();
        la_id_nextel = new javax.swing.JLabel();
        tf_id_nextel = new javax.swing.JTextField();
        la_email = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        la_celular1 = new javax.swing.JLabel();
        tf_celular1 = new javax.swing.JTextField();
        se_separador3 = new javax.swing.JSeparator();
        la_titulo_dados_bancarios = new javax.swing.JLabel();
        la_banco1 = new javax.swing.JLabel();
        tf_banco1 = new javax.swing.JTextField();
        la_agencia1 = new javax.swing.JLabel();
        tf_agencia1 = new javax.swing.JTextField();
        la_conta_corrente1 = new javax.swing.JLabel();
        tf_conta_corrente1 = new javax.swing.JTextField();
        la_banco2 = new javax.swing.JLabel();
        tf_banco2 = new javax.swing.JTextField();
        la_agencia2 = new javax.swing.JLabel();
        tf_agencia2 = new javax.swing.JTextField();
        la_conta_corrente2 = new javax.swing.JLabel();
        tf_conta_corrente2 = new javax.swing.JTextField();
        la_banco3 = new javax.swing.JLabel();
        tf_banco3 = new javax.swing.JTextField();
        la_agencia3 = new javax.swing.JLabel();
        tf_agencia3 = new javax.swing.JTextField();
        la_conta_corrente3 = new javax.swing.JLabel();
        tf_conta_corrente3 = new javax.swing.JTextField();
        se_separador4 = new javax.swing.JSeparator();
        la_titulo1_dados_vendedor = new javax.swing.JLabel();
        la_nome_vendedor = new javax.swing.JLabel();
        tf_nome_vendedor = new javax.swing.JTextField();
        la_id_nextel_vendedor = new javax.swing.JLabel();
        tf_id_nextel_vendedor = new javax.swing.JTextField();
        la_telefone_vendedor = new javax.swing.JLabel();
        tf_telefone_vendedor = new javax.swing.JTextField();
        la_email_vendedor = new javax.swing.JLabel();
        tf_email_vendedor = new javax.swing.JTextField();
        la_observacoes = new javax.swing.JLabel();
        sp_painel_rolagem = new javax.swing.JScrollPane();
        ta_observacoes = new javax.swing.JTextArea();
        bo_salvar = new javax.swing.JButton();
        bo_limpar = new javax.swing.JButton();
        bo_cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        la_nome_titulo_empresa1 = new javax.swing.JLabel();
        bo_filtro_nome = new javax.swing.JButton();
        tf_campo_pesquisa = new javax.swing.JTextField();
        bo_atualizar1 = new javax.swing.JButton();
        bo_editar_cliente1 = new javax.swing.JButton();
        bo_excluir_cliente1 = new javax.swing.JButton();
        bo_consulta_completa1 = new javax.swing.JButton();

        bo_atualizar.setBackground(new java.awt.Color(0, 0, 204));
        bo_atualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bo_atualizar.setText("Atualizar Tabela");

        bo_editar_cliente.setBackground(new java.awt.Color(255, 255, 0));
        bo_editar_cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bo_editar_cliente.setText("Editar Cliente Selecionado");

        bo_excluir_cliente.setBackground(new java.awt.Color(255, 0, 0));
        bo_excluir_cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bo_excluir_cliente.setText("Excluir Registro");
        bo_excluir_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_excluir_clienteActionPerformed(evt);
            }
        });

        bo_consulta_completa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bo_consulta_completa.setText("Consultar Todos os Dados do Cliente");
        bo_consulta_completa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_consulta_completaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedores - Japa Auto Peças");
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        la_titulo1_dados_empresa.setMaximumSize(new java.awt.Dimension(560, 600));
        la_titulo1_dados_empresa.setMinimumSize(new java.awt.Dimension(560, 600));
        la_titulo1_dados_empresa.setPreferredSize(new java.awt.Dimension(560, 600));

        la_titulo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        la_titulo.setText("Cadastro de Fornecedores");

        la_nome_titulo_empresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        la_nome_titulo_empresa.setText("Dados da empresa");

        la_nome_fantasia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_nome_fantasia.setText("Nome Fantasia:");

        la_razao_social.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_razao_social.setText("Razão Social:");

        tf_razao_social.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_razao_socialActionPerformed(evt);
            }
        });

        la_cnpj.setText("CNPJ:");

        la_inscricao_estadual.setText("Inscrição Estadual:");

        la_titulo1_dados_endereco_empresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        la_titulo1_dados_endereco_empresa.setText("Endereço e Contato da Empresa");

        la_rua.setText("Rua:");

        la_numero.setText("Número:");

        la_bairro.setText("Bairro:");

        la_cidade.setText("Cidade:");

        tf_cidade.setText("Caraguatatuba");

        la_cep.setText("CEP:");

        tf_cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cepActionPerformed(evt);
            }
        });

        la_telefone1.setText("Telefone1:");

        la_telefone2.setText("Telefone2:");

        la_celular.setText("Celular:");

        la_id_nextel.setText("Id Nextel:");

        la_email.setText("E-mail:");

        la_celular1.setText("Data de Cadastro:");

        la_titulo_dados_bancarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        la_titulo_dados_bancarios.setText("Dados Bancários");

        la_banco1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_banco1.setText("Nome do Banco 1:");

        la_agencia1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_agencia1.setText("Agência 1:");

        la_conta_corrente1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_conta_corrente1.setText("Conta Corrente 1:");

        la_banco2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_banco2.setText("Nome do Banco 2:");

        la_agencia2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_agencia2.setText("Agência 2:");

        la_conta_corrente2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_conta_corrente2.setText("Conta Corrente 2:");

        la_banco3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_banco3.setText("Nome do Banco 3:");

        la_agencia3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_agencia3.setText("Agência 3:");

        la_conta_corrente3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_conta_corrente3.setText("Conta Corrente 3:");

        la_titulo1_dados_vendedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        la_titulo1_dados_vendedor.setText("Contato do Vendedor");

        la_nome_vendedor.setText("Nome do Vendedor:");

        la_id_nextel_vendedor.setText("ID Nextel:");

        la_telefone_vendedor.setText("Telefone: ");

        la_email_vendedor.setText("E-mail:");

        la_observacoes.setText("Observações:");

        ta_observacoes.setColumns(20);
        ta_observacoes.setRows(5);
        sp_painel_rolagem.setViewportView(ta_observacoes);

        bo_salvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bo_salvar.setText("Salvar");
        bo_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_salvarActionPerformed(evt);
            }
        });

        bo_limpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bo_limpar.setText("Limpar Dados");
        bo_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_limparActionPerformed(evt);
            }
        });

        bo_cancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bo_cancelar.setText("Cancelar");
        bo_cancelar.setMaximumSize(new java.awt.Dimension(117, 25));
        bo_cancelar.setMinimumSize(new java.awt.Dimension(117, 25));
        bo_cancelar.setPreferredSize(new java.awt.Dimension(117, 25));
        bo_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_cancelarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome Fantasia", "CNPJ", "Inscrição Est.", "Telefone Emp.", "Vendedor", "Telefone Ven."
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        la_nome_titulo_empresa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        la_nome_titulo_empresa1.setText("Consulta Resumida");

        bo_filtro_nome.setText("Filtrar por Nome Fantasia");
        bo_filtro_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_filtro_nomeActionPerformed(evt);
            }
        });

        bo_atualizar1.setBackground(new java.awt.Color(0, 0, 204));
        bo_atualizar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bo_atualizar1.setText("Atualizar Tabela");
        bo_atualizar1.setMaximumSize(new java.awt.Dimension(259, 23));
        bo_atualizar1.setMinimumSize(new java.awt.Dimension(259, 23));
        bo_atualizar1.setPreferredSize(new java.awt.Dimension(259, 23));

        bo_editar_cliente1.setBackground(new java.awt.Color(255, 255, 0));
        bo_editar_cliente1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bo_editar_cliente1.setText("Editar Fornecedor Selecionado");
        bo_editar_cliente1.setMaximumSize(new java.awt.Dimension(259, 23));
        bo_editar_cliente1.setMinimumSize(new java.awt.Dimension(259, 23));
        bo_editar_cliente1.setPreferredSize(new java.awt.Dimension(259, 23));

        bo_excluir_cliente1.setBackground(new java.awt.Color(255, 0, 0));
        bo_excluir_cliente1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bo_excluir_cliente1.setText("Excluir Registro");
        bo_excluir_cliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_excluir_cliente1ActionPerformed(evt);
            }
        });

        bo_consulta_completa1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bo_consulta_completa1.setText("Consultar Todos os Dados do Fornecedor");
        bo_consulta_completa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_consulta_completa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout la_titulo1_dados_empresaLayout = new javax.swing.GroupLayout(la_titulo1_dados_empresa);
        la_titulo1_dados_empresa.setLayout(la_titulo1_dados_empresaLayout);
        la_titulo1_dados_empresaLayout.setHorizontalGroup(
            la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(se_separador1)
                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                .addComponent(la_titulo1_dados_vendedor)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, la_titulo1_dados_empresaLayout.createSequentialGroup()
                                .addComponent(la_nome_vendedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_nome_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(la_id_nextel_vendedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_id_nextel_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(la_telefone_vendedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_telefone_vendedor))
                            .addComponent(se_separador4)
                            .addComponent(se_separador3)
                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(la_nome_fantasia)
                                    .addComponent(la_cnpj))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nome_fantasia, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(tf_cnpj))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(la_razao_social)
                                    .addComponent(la_inscricao_estadual))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_inscricao_estadual)
                                    .addComponent(tf_razao_social)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, la_titulo1_dados_empresaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(se_separador2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(la_titulo_dados_bancarios, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(la_titulo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, la_titulo1_dados_empresaLayout.createSequentialGroup()
                                        .addComponent(la_id_nextel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_id_nextel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(la_email)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(la_celular1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_celular1))
                                    .addComponent(la_nome_titulo_empresa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, la_titulo1_dados_empresaLayout.createSequentialGroup()
                                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_rua)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tf_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(la_numero)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_cep)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(la_telefone1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_bairro)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(la_cidade)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_cidade, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_telefone2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(la_celular)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_celular))))
                                    .addComponent(la_titulo1_dados_endereco_empresa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_banco1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_banco1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_banco2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_banco2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_banco3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_banco3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(28, 28, 28)
                                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_agencia1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_agencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_agencia2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_agencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_agencia3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_agencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_conta_corrente1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_conta_corrente1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_conta_corrente2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_conta_corrente2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_conta_corrente3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_conta_corrente3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(la_email_vendedor)
                                    .addComponent(la_observacoes))
                                .addGap(32, 32, 32)
                                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_email_vendedor)
                                    .addComponent(sp_painel_rolagem)))
                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                .addComponent(bo_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(bo_limpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bo_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bo_editar_cliente1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(bo_atualizar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bo_excluir_cliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bo_consulta_completa1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, la_titulo1_dados_empresaLayout.createSequentialGroup()
                                .addComponent(la_nome_titulo_empresa1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_campo_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bo_filtro_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        la_titulo1_dados_empresaLayout.setVerticalGroup(
            la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(la_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(se_separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(la_nome_titulo_empresa)
                    .addComponent(la_nome_titulo_empresa1)
                    .addComponent(bo_filtro_nome)
                    .addComponent(tf_campo_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_nome_fantasia)
                            .addComponent(tf_nome_fantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_razao_social)
                            .addComponent(tf_razao_social, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_cnpj)
                            .addComponent(tf_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_inscricao_estadual)
                            .addComponent(tf_inscricao_estadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(se_separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(la_titulo1_dados_endereco_empresa)
                        .addGap(18, 18, 18)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_rua)
                            .addComponent(tf_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_numero)
                            .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_bairro)
                            .addComponent(tf_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_cidade)
                            .addComponent(tf_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_cep)
                            .addComponent(tf_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_telefone1)
                            .addComponent(tf_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_telefone2)
                            .addComponent(tf_telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_celular)
                            .addComponent(tf_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_id_nextel)
                            .addComponent(tf_id_nextel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_email)
                            .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_celular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_celular1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(se_separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(la_titulo_dados_bancarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_banco1)
                            .addComponent(tf_banco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_conta_corrente1)
                            .addComponent(la_agencia1)
                            .addComponent(tf_agencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_conta_corrente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_banco2)
                            .addComponent(tf_banco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_conta_corrente2)
                            .addComponent(la_agencia2)
                            .addComponent(tf_agencia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_conta_corrente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_banco3)
                            .addComponent(tf_banco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_conta_corrente3)
                            .addComponent(la_agencia3)
                            .addComponent(tf_agencia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_conta_corrente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(se_separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(la_titulo1_dados_vendedor)
                        .addGap(18, 18, 18)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_nome_vendedor)
                            .addComponent(tf_nome_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_id_nextel_vendedor)
                            .addComponent(tf_id_nextel_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_telefone_vendedor)
                            .addComponent(tf_telefone_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_email_vendedor)
                            .addComponent(tf_email_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bo_editar_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bo_excluir_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bo_atualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bo_consulta_completa1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(la_observacoes)
                            .addComponent(sp_painel_rolagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bo_salvar)
                            .addComponent(bo_limpar)
                            .addComponent(bo_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(la_titulo1_dados_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, 1245, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(la_titulo1_dados_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bo_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_cancelarActionPerformed
        tf_nome_fantasia.requestFocus();
        int opcao = JOptionPane.showConfirmDialog
        (null, "Deseja sair do cadastro?", "Invicta Code", JOptionPane.INFORMATION_MESSAGE);
        if(opcao == 0)
        {
            chamarInicial();
            dispose();
        }
    }//GEN-LAST:event_bo_cancelarActionPerformed

    private void bo_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_limparActionPerformed

    }//GEN-LAST:event_bo_limparActionPerformed

    private void bo_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_salvarActionPerformed

    }//GEN-LAST:event_bo_salvarActionPerformed

    private void tf_cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cepActionPerformed

    private void tf_razao_socialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_razao_socialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_razao_socialActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        tf_nome_fantasia.requestFocus();
        int opcao = JOptionPane.showConfirmDialog
        (null, "Deseja sair do cadastro?", "Invicta Code", JOptionPane.INFORMATION_MESSAGE);
        if(opcao == 0)
        {
            chamarInicial();
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void bo_filtro_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_filtro_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo_filtro_nomeActionPerformed

    private void bo_excluir_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_excluir_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo_excluir_clienteActionPerformed

    private void bo_consulta_completaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_consulta_completaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo_consulta_completaActionPerformed

    private void bo_excluir_cliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_excluir_cliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo_excluir_cliente1ActionPerformed

    private void bo_consulta_completa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_consulta_completa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo_consulta_completa1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new CadastroFornecedor().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CadastroFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bo_atualizar;
    private javax.swing.JButton bo_atualizar1;
    private javax.swing.JButton bo_cancelar;
    private javax.swing.JButton bo_consulta_completa;
    private javax.swing.JButton bo_consulta_completa1;
    private javax.swing.JButton bo_editar_cliente;
    private javax.swing.JButton bo_editar_cliente1;
    private javax.swing.JButton bo_excluir_cliente;
    private javax.swing.JButton bo_excluir_cliente1;
    private javax.swing.JButton bo_filtro_nome;
    private javax.swing.JButton bo_limpar;
    private javax.swing.JButton bo_salvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel la_agencia1;
    private javax.swing.JLabel la_agencia2;
    private javax.swing.JLabel la_agencia3;
    private javax.swing.JLabel la_bairro;
    private javax.swing.JLabel la_banco1;
    private javax.swing.JLabel la_banco2;
    private javax.swing.JLabel la_banco3;
    private javax.swing.JLabel la_celular;
    private javax.swing.JLabel la_celular1;
    private javax.swing.JLabel la_cep;
    private javax.swing.JLabel la_cidade;
    private javax.swing.JLabel la_cnpj;
    private javax.swing.JLabel la_conta_corrente1;
    private javax.swing.JLabel la_conta_corrente2;
    private javax.swing.JLabel la_conta_corrente3;
    private javax.swing.JLabel la_email;
    private javax.swing.JLabel la_email_vendedor;
    private javax.swing.JLabel la_id_nextel;
    private javax.swing.JLabel la_id_nextel_vendedor;
    private javax.swing.JLabel la_inscricao_estadual;
    private javax.swing.JLabel la_nome_fantasia;
    private javax.swing.JLabel la_nome_titulo_empresa;
    private javax.swing.JLabel la_nome_titulo_empresa1;
    private javax.swing.JLabel la_nome_vendedor;
    private javax.swing.JLabel la_numero;
    private javax.swing.JLabel la_observacoes;
    private javax.swing.JLabel la_razao_social;
    private javax.swing.JLabel la_rua;
    private javax.swing.JLabel la_telefone1;
    private javax.swing.JLabel la_telefone2;
    private javax.swing.JLabel la_telefone_vendedor;
    private javax.swing.JLabel la_titulo;
    private javax.swing.JPanel la_titulo1_dados_empresa;
    private javax.swing.JLabel la_titulo1_dados_endereco_empresa;
    private javax.swing.JLabel la_titulo1_dados_vendedor;
    private javax.swing.JLabel la_titulo_dados_bancarios;
    private javax.swing.JSeparator se_separador1;
    private javax.swing.JSeparator se_separador2;
    private javax.swing.JSeparator se_separador3;
    private javax.swing.JSeparator se_separador4;
    private javax.swing.JScrollPane sp_painel_rolagem;
    private javax.swing.JTextArea ta_observacoes;
    private javax.swing.JTextField tf_agencia1;
    private javax.swing.JTextField tf_agencia2;
    private javax.swing.JTextField tf_agencia3;
    private javax.swing.JTextField tf_bairro;
    private javax.swing.JTextField tf_banco1;
    private javax.swing.JTextField tf_banco2;
    private javax.swing.JTextField tf_banco3;
    private javax.swing.JTextField tf_campo_pesquisa;
    private javax.swing.JTextField tf_celular;
    private javax.swing.JTextField tf_celular1;
    private javax.swing.JTextField tf_cep;
    private javax.swing.JTextField tf_cidade;
    private javax.swing.JTextField tf_cnpj;
    private javax.swing.JTextField tf_conta_corrente1;
    private javax.swing.JTextField tf_conta_corrente2;
    private javax.swing.JTextField tf_conta_corrente3;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_email_vendedor;
    private javax.swing.JTextField tf_id_nextel;
    private javax.swing.JTextField tf_id_nextel_vendedor;
    private javax.swing.JTextField tf_inscricao_estadual;
    private javax.swing.JTextField tf_nome_fantasia;
    private javax.swing.JTextField tf_nome_vendedor;
    private javax.swing.JTextField tf_numero;
    private javax.swing.JTextField tf_razao_social;
    private javax.swing.JTextField tf_rua;
    private javax.swing.JTextField tf_telefone1;
    private javax.swing.JTextField tf_telefone2;
    private javax.swing.JTextField tf_telefone_vendedor;
    // End of variables declaration//GEN-END:variables

    public void lookandfeel() throws ClassNotFoundException {
        try {
            UIManager.setLookAndFeel(seta_look);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }
    
    void setarIcone()
    {
        URL url = this.getClass().getResource("cubo_grande.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }
    
    void chamarMesma() throws ClassNotFoundException {
        CadastroFornecedor ceu = new CadastroFornecedor();
        ceu.setVisible(true);
    }
        
    void chamarInicial() 
    {
        //Chama a home do sistema
        TelaInicial ti = new TelaInicial();
        ti.setVisible(true);
    }    
        
    void fecharMesma() throws ClassNotFoundException
    {
      tf_nome_fantasia.requestFocus();
      int opcao = JOptionPane.showConfirmDialog
        (null, "Deseja sair do cadastro?", "Invicta Code", JOptionPane.INFORMATION_MESSAGE);
        if(opcao == 0)
        {
            chamarInicial();
            dispose();
        }
        else
        {
            chamarMesma();
        }  
      
    }}

