package Cadastro;

import Conexao.AcessoBD;
import Gerenciamento.TelaInicial;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Nunweiler
 */
public final class CadastroCliente extends javax.swing.JFrame {

    String seta_look = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
    AcessoBD database = new AcessoBD("japa");
    MaskFormatter maskDataNascimento, maskCNPJ, maskTel1, maskTel2, maskDataCadastro, maskPorcentagem, maskCEP, maskCPF, maskCel;
    
    public CadastroCliente() throws ClassNotFoundException, ParseException {
        initComponents();
        setLocationRelativeTo(null);
        lookandfeel();
        setarIcone();
        listarClientes();
        tf_numero.setText(""+0);
        tf_limite_compras.setText(""+0);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        la_titulo1_dados_empresa = new javax.swing.JPanel();
        la_titulo = new javax.swing.JLabel();
        se_separador1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        la_nome = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        la_dataNascimento = new javax.swing.JLabel();
        try {
            maskDataNascimento = new MaskFormatter("##/##/####");
        } catch (Exception e) {
            System.err.println("Erro ao setar mascara");
        }
        tf_dataNascimento = new JFormattedTextField(maskDataNascimento);
        la_rg = new javax.swing.JLabel();
        tf_rg = new javax.swing.JTextField();
        la_cpf = new javax.swing.JLabel();
        try {
            maskCPF= new MaskFormatter("###.###.###-##");
        } catch (Exception e) {
            System.err.println("Erro ao setar mascara");
        }
        tf_cpf = new JFormattedTextField(maskCPF);
        la_cnpj = new javax.swing.JLabel();
        try {
            maskCNPJ = new MaskFormatter("##.###.###/####-##");
        } catch (Exception e) {
            System.err.println("Erro ao setar mascara");
        }
        tf_cnpj = new JFormattedTextField(maskCNPJ);
        la_inscricao_estadual = new javax.swing.JLabel();
        tf_nome_fantasia = new javax.swing.JTextField();
        la_razao_social = new javax.swing.JLabel();
        tf_razao_social = new javax.swing.JTextField();
        se_separador2 = new javax.swing.JSeparator();
        la_titulo1_dados_contato = new javax.swing.JLabel();
        la_rua = new javax.swing.JLabel();
        tf_rua = new javax.swing.JTextField();
        la_numero = new javax.swing.JLabel();
        tf_numero = new javax.swing.JTextField();
        la_bairro = new javax.swing.JLabel();
        tf_bairro = new javax.swing.JTextField();
        la_cidade = new javax.swing.JLabel();
        tf_cidade = new javax.swing.JTextField();
        la_cep = new javax.swing.JLabel();

        try {
            maskCEP= new MaskFormatter("#####-###");
        } catch (Exception e) {
            System.err.println("Erro ao setar mascara");
        }
        tf_cep = new JFormattedTextField(maskCEP);
        la_telefone1 = new javax.swing.JLabel();
        try {
            maskTel1= new MaskFormatter("(##)####-####");
        } catch (Exception e) {
            System.err.println("Erro ao setar mascara");
        }
        tf_telefone1 = new JFormattedTextField(maskTel1);
        la_telefone2 = new javax.swing.JLabel();
        try {
            maskTel2= new MaskFormatter("(##)####-####");
        } catch (Exception e) {
            System.err.println("Erro ao setar mascara");
        }
        tf_telefone2 = new JFormattedTextField(maskTel2);
        la_celular = new javax.swing.JLabel();
        try {
            maskCel= new MaskFormatter("(##)####-####");
        } catch (Exception e) {
            System.err.println("Erro ao setar mascara");
        }
        tf_celular = new JFormattedTextField(maskCel);
        la_id_nextel = new javax.swing.JLabel();
        tf_id_nextel = new javax.swing.JTextField();
        la_email = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        se_separador3 = new javax.swing.JSeparator();
        la_titulo_informacoes = new javax.swing.JLabel();
        la_responsavel_compras = new javax.swing.JLabel();
        tf_responsavel_compras = new javax.swing.JTextField();
        la_ramo_atividade = new javax.swing.JLabel();
        com_atividades = new javax.swing.JComboBox();
        la_data_cadastro = new javax.swing.JLabel();
        try {
            maskDataCadastro= new MaskFormatter("##/##/####");
        } catch (Exception e) {
            System.err.println("Erro ao setar mascara");
        }
        tf_data_cadastro = new JFormattedTextField(maskDataCadastro);
        la_porcentagem_desconto = new javax.swing.JLabel();

        try {
            maskPorcentagem= new MaskFormatter("##%");
        } catch (Exception e) {
            System.err.println("Erro ao setar mascara");
        }

        tf_porcentagem_desconto = new JFormattedTextField(maskPorcentagem);
        la_limite_compras = new javax.swing.JLabel();
        tf_limite_compras = new javax.swing.JTextField();
        se_separador4 = new javax.swing.JSeparator();
        la_titulo_observacoes = new javax.swing.JLabel();
        sp_painel_rolagem = new javax.swing.JScrollPane();
        ta_observacoes = new javax.swing.JTextArea();
        bo_salvar = new javax.swing.JButton();
        bo_limpar = new javax.swing.JButton();
        bo_cancelar = new javax.swing.JButton();
        la_nome_fantasia1 = new javax.swing.JLabel();
        tf_inscricao_estadual = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_cliente = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        bo_editar_cliente = new javax.swing.JButton();
        bo_atualizar = new javax.swing.JButton();
        bo_consulta_completa = new javax.swing.JButton();
        bo_excluir_cliente = new javax.swing.JButton();
        bo_filtro_nome = new javax.swing.JButton();
        tf_campo_pesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes - Japa Auto Peças");
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        la_titulo1_dados_empresa.setMaximumSize(new java.awt.Dimension(560, 600));
        la_titulo1_dados_empresa.setMinimumSize(new java.awt.Dimension(560, 600));
        la_titulo1_dados_empresa.setPreferredSize(new java.awt.Dimension(560, 600));

        la_titulo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        la_titulo.setText("Cadastro de Clientes");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Dados da empresa");

        la_nome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_nome.setText("Nome*:");

        la_dataNascimento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_dataNascimento.setText("Data de Nascimento:");

        la_rg.setText("RG:");

        la_cpf.setText("CPF*:");

        la_cnpj.setText("CNPJ:");

        la_inscricao_estadual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_inscricao_estadual.setText("Inscrição Estadual*:");

        la_razao_social.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_razao_social.setText("Razão Social:");

        tf_razao_social.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_razao_socialActionPerformed(evt);
            }
        });

        la_titulo1_dados_contato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        la_titulo1_dados_contato.setText("Endereço e Contato");

        la_rua.setText("Rua:");

        la_numero.setText("Número:");

        la_bairro.setText("Bairro:");

        la_cidade.setText("Cidade:");

        la_cep.setText("CEP:");

        tf_cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cepActionPerformed(evt);
            }
        });

        la_telefone1.setText("Telefone1:");

        la_telefone2.setText("Telefone2:");

        tf_telefone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_telefone2ActionPerformed(evt);
            }
        });

        la_celular.setText("Celular:");

        la_id_nextel.setText("Id Nextel:");

        la_email.setText("E-mail:");

        la_titulo_informacoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        la_titulo_informacoes.setText("Informações");

        la_responsavel_compras.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_responsavel_compras.setText("Responsável pelas compras*:");

        la_ramo_atividade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_ramo_atividade.setText("Ramo de Atividades:");

        com_atividades.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mecânico", "Empresa", "Auto Peças", "Eletricista", "Autonomo" }));
        com_atividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_atividadesActionPerformed(evt);
            }
        });

        la_data_cadastro.setText("Data de Cadastro*:");

        tf_data_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_data_cadastroActionPerformed(evt);
            }
        });

        la_porcentagem_desconto.setText("Porcentagem de Desconto:");

        tf_porcentagem_desconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_porcentagem_descontoActionPerformed(evt);
            }
        });

        la_limite_compras.setText("Limite de Compras:");

        tf_limite_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_limite_comprasActionPerformed(evt);
            }
        });

        la_titulo_observacoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        la_titulo_observacoes.setText("Observações:");

        ta_observacoes.setColumns(20);
        ta_observacoes.setRows(5);
        sp_painel_rolagem.setViewportView(ta_observacoes);

        bo_salvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bo_salvar.setText("Salvar");
        bo_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_salvarActionPerformed(evt);
            }
        });

        bo_limpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bo_limpar.setText("Limpar Dados");
        bo_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_limparActionPerformed(evt);
            }
        });

        bo_cancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bo_cancelar.setText("Cancelar");
        bo_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_cancelarActionPerformed(evt);
            }
        });

        la_nome_fantasia1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        la_nome_fantasia1.setText("Nome Fantasia:");

        jt_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CNPJ", "Nome Fantasia", "Cidade", "Responsável"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_cliente);
        jt_cliente.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jt_cliente.getColumnModel().getColumnCount() > 0) {
            jt_cliente.getColumnModel().getColumn(0).setResizable(false);
            jt_cliente.getColumnModel().getColumn(1).setResizable(false);
            jt_cliente.getColumnModel().getColumn(2).setResizable(false);
            jt_cliente.getColumnModel().getColumn(3).setResizable(false);
            jt_cliente.getColumnModel().getColumn(4).setResizable(false);
            jt_cliente.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Consulta Resumida de Clientes:");

        bo_editar_cliente.setBackground(new java.awt.Color(255, 255, 0));
        bo_editar_cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bo_editar_cliente.setText("Editar Cliente Selecionado");
        bo_editar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_editar_clienteActionPerformed(evt);
            }
        });

        bo_atualizar.setBackground(new java.awt.Color(0, 0, 204));
        bo_atualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bo_atualizar.setText("Atualizar Tabela");
        bo_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_atualizarActionPerformed(evt);
            }
        });

        bo_consulta_completa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bo_consulta_completa.setText("Consultar Todos os Dados do Cliente");
        bo_consulta_completa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_consulta_completaActionPerformed(evt);
            }
        });

        bo_excluir_cliente.setBackground(new java.awt.Color(255, 0, 0));
        bo_excluir_cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bo_excluir_cliente.setText("Excluir Registro");
        bo_excluir_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_excluir_clienteActionPerformed(evt);
            }
        });

        bo_filtro_nome.setText("Filtrar por Nome");

        javax.swing.GroupLayout la_titulo1_dados_empresaLayout = new javax.swing.GroupLayout(la_titulo1_dados_empresa);
        la_titulo1_dados_empresa.setLayout(la_titulo1_dados_empresaLayout);
        la_titulo1_dados_empresaLayout.setHorizontalGroup(
            la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                        .addComponent(la_responsavel_compras)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_responsavel_compras, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(la_ramo_atividade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(com_atividades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                        .addComponent(la_data_cadastro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_data_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(la_porcentagem_desconto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_porcentagem_desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(la_limite_compras)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_limite_compras))
                                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                        .addComponent(la_id_nextel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_id_nextel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(la_email)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_email))
                                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                        .addComponent(bo_salvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bo_limpar)
                                        .addGap(113, 113, 113)
                                        .addComponent(bo_cancelar))
                                    .addComponent(la_titulo_informacoes)
                                    .addComponent(la_titulo)
                                    .addComponent(jLabel1)
                                    .addComponent(la_titulo1_dados_contato)
                                    .addComponent(se_separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(se_separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(la_titulo_observacoes)
                                    .addComponent(sp_painel_rolagem, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_rua)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_rua)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(la_numero)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_cep)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(la_telefone1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_bairro)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(la_cidade))
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_telefone2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(la_celular)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_celular))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, la_titulo1_dados_empresaLayout.createSequentialGroup()
                                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addComponent(la_nome)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(la_dataNascimento)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(la_rg)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tf_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                        .addComponent(la_razao_social)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tf_razao_social))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                        .addComponent(la_cpf)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(la_cnpj)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(tf_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(10, 10, 10)
                                                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                        .addComponent(la_inscricao_estadual)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(tf_inscricao_estadual))
                                                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                                        .addComponent(la_nome_fantasia1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tf_nome_fantasia)))))
                                        .addGap(1, 1, 1))))
                            .addComponent(se_separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                .addGap(477, 477, 477)
                                .addComponent(tf_cidade)))
                        .addGap(18, 18, 18)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                                .addComponent(tf_campo_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bo_filtro_nome))
                            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bo_editar_cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(bo_atualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bo_excluir_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bo_consulta_completa, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))))
                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(se_separador1)))
                .addContainerGap())
        );
        la_titulo1_dados_empresaLayout.setVerticalGroup(
            la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(la_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(se_separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(bo_filtro_nome)
                    .addComponent(tf_campo_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_nome)
                            .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_dataNascimento)
                            .addComponent(tf_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_rg)
                            .addComponent(tf_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_cpf)
                            .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_cnpj)
                            .addComponent(tf_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nome_fantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_nome_fantasia1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_razao_social)
                            .addComponent(tf_razao_social, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_inscricao_estadual)
                            .addComponent(tf_inscricao_estadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(se_separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(la_titulo1_dados_contato)
                        .addGap(18, 18, 18)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_rua)
                            .addComponent(tf_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_numero)
                            .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_bairro)
                            .addComponent(tf_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_cidade)
                            .addComponent(tf_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_cep)
                            .addComponent(tf_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_telefone1)
                            .addComponent(tf_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_telefone2)
                            .addComponent(tf_telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_celular)
                            .addComponent(tf_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_id_nextel)
                            .addComponent(tf_id_nextel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_email)
                            .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(se_separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(la_titulo_informacoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_responsavel_compras)
                            .addComponent(tf_responsavel_compras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_ramo_atividade)
                            .addComponent(com_atividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_data_cadastro)
                            .addComponent(tf_data_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_porcentagem_desconto)
                            .addComponent(tf_porcentagem_desconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la_limite_compras)
                            .addComponent(tf_limite_compras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(se_separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bo_editar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bo_excluir_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bo_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bo_consulta_completa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(la_titulo1_dados_empresaLayout.createSequentialGroup()
                        .addComponent(la_titulo_observacoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_painel_rolagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(la_titulo1_dados_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bo_salvar)
                            .addComponent(bo_limpar)
                            .addComponent(bo_cancelar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(la_titulo1_dados_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(la_titulo1_dados_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );

        this.setLocationRelativeTo(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_razao_socialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_razao_socialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_razao_socialActionPerformed

    private void tf_cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cepActionPerformed

    private void tf_data_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_data_cadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_data_cadastroActionPerformed

    private void tf_porcentagem_descontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_porcentagem_descontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_porcentagem_descontoActionPerformed

    private void tf_limite_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_limite_comprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_limite_comprasActionPerformed

    private void com_atividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_atividadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_atividadesActionPerformed

    private void bo_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_salvarActionPerformed
        checarCamposObrigatorios();
       
    }//GEN-LAST:event_bo_salvarActionPerformed

    private void bo_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_limparActionPerformed
        limparCampos();
    }//GEN-LAST:event_bo_limparActionPerformed

    private void bo_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_cancelarActionPerformed
        tf_nome.requestFocus();
        int opcao = JOptionPane.showConfirmDialog
        (null, "Deseja sair do cadastro?", "Invicta Code", JOptionPane.INFORMATION_MESSAGE);
        if(opcao == 0)
        {
            chamarInicial();
            dispose();
        }
    }//GEN-LAST:event_bo_cancelarActionPerformed

    private void tf_telefone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_telefone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_telefone2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        tf_nome.requestFocus();
        int opcao = JOptionPane.showConfirmDialog
        (null, "Deseja sair do cadastro?", "Invicta Code", JOptionPane.INFORMATION_MESSAGE);
        if(opcao == 0)
        {
            chamarInicial();
            dispose();

        }else if (opcao == 1 || opcao == 2)
        {
            try {
                chamarMesma();
            } catch (ClassNotFoundException | ParseException ex) {
                Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
    }//GEN-LAST:event_formWindowClosing

    private void bo_excluir_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_excluir_clienteActionPerformed
        int codigo = (int) jt_cliente.getModel().getValueAt(jt_cliente.getSelectedRow() ,0);
        //JOptionPane.showMessageDialog(this, jt_cliente.getSelectedRow());
        
        
        excluirCliente(codigo);
        
        DefaultTableModel modelo = (DefaultTableModel) jt_cliente.getModel();
               
        modelo.removeRow(jt_cliente.getSelectedRow());
        
    }//GEN-LAST:event_bo_excluir_clienteActionPerformed

    private void bo_consulta_completaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_consulta_completaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo_consulta_completaActionPerformed

    private void bo_editar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_editar_clienteActionPerformed
        int codigo = (int) jt_cliente.getModel().getValueAt(jt_cliente.getSelectedRow() ,0);
        String nome              = (String) jt_cliente.getModel().getValueAt(jt_cliente.getSelectedRow() ,1);
        String cnpj              = (String) jt_cliente.getModel().getValueAt(jt_cliente.getSelectedRow() ,2);
        String nome_fantasia     = (String) jt_cliente.getModel().getValueAt(jt_cliente.getSelectedRow() ,3);
        String cidade            = (String) jt_cliente.getModel().getValueAt(jt_cliente.getSelectedRow() ,4);
        String nome_responsavel  = (String) jt_cliente.getModel().getValueAt(jt_cliente.getSelectedRow() ,5);
        
        //JOptionPane.showMessageDialog(this, cnpj, cidade, codigo);
        
        Edicao.EdicaoCliente ep = new Edicao.EdicaoCliente(codigo,nome,cnpj,
            nome_fantasia, cidade, nome_responsavel);

        ep.setVisible(true);
        dispose();
    }//GEN-LAST:event_bo_editar_clienteActionPerformed

    private void bo_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_atualizarActionPerformed
        limparClienteJTable();
        listarClientes();
    }//GEN-LAST:event_bo_atualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new CadastroCliente().setVisible(true);
                } catch (ClassNotFoundException | ParseException ex) {
                    Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bo_atualizar;
    private javax.swing.JButton bo_cancelar;
    private javax.swing.JButton bo_consulta_completa;
    private javax.swing.JButton bo_editar_cliente;
    private javax.swing.JButton bo_excluir_cliente;
    private javax.swing.JButton bo_filtro_nome;
    private javax.swing.JButton bo_limpar;
    private javax.swing.JButton bo_salvar;
    private javax.swing.JComboBox com_atividades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_cliente;
    private javax.swing.JLabel la_bairro;
    private javax.swing.JLabel la_celular;
    private javax.swing.JLabel la_cep;
    private javax.swing.JLabel la_cidade;
    private javax.swing.JLabel la_cnpj;
    private javax.swing.JLabel la_cpf;
    private javax.swing.JLabel la_dataNascimento;
    private javax.swing.JLabel la_data_cadastro;
    private javax.swing.JLabel la_email;
    private javax.swing.JLabel la_id_nextel;
    private javax.swing.JLabel la_inscricao_estadual;
    private javax.swing.JLabel la_limite_compras;
    private javax.swing.JLabel la_nome;
    private javax.swing.JLabel la_nome_fantasia1;
    private javax.swing.JLabel la_numero;
    private javax.swing.JLabel la_porcentagem_desconto;
    private javax.swing.JLabel la_ramo_atividade;
    private javax.swing.JLabel la_razao_social;
    private javax.swing.JLabel la_responsavel_compras;
    private javax.swing.JLabel la_rg;
    private javax.swing.JLabel la_rua;
    private javax.swing.JLabel la_telefone1;
    private javax.swing.JLabel la_telefone2;
    private javax.swing.JLabel la_titulo;
    private javax.swing.JLabel la_titulo1_dados_contato;
    private javax.swing.JPanel la_titulo1_dados_empresa;
    private javax.swing.JLabel la_titulo_informacoes;
    private javax.swing.JLabel la_titulo_observacoes;
    private javax.swing.JSeparator se_separador1;
    private javax.swing.JSeparator se_separador2;
    private javax.swing.JSeparator se_separador3;
    private javax.swing.JSeparator se_separador4;
    private javax.swing.JScrollPane sp_painel_rolagem;
    private javax.swing.JTextArea ta_observacoes;
    private javax.swing.JTextField tf_bairro;
    private javax.swing.JTextField tf_campo_pesquisa;
    private javax.swing.JTextField tf_celular;
    private javax.swing.JTextField tf_cep;
    private javax.swing.JTextField tf_cidade;
    private javax.swing.JTextField tf_cnpj;
    private javax.swing.JTextField tf_cpf;
    private javax.swing.JTextField tf_dataNascimento;
    private javax.swing.JTextField tf_data_cadastro;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_id_nextel;
    private javax.swing.JTextField tf_inscricao_estadual;
    private javax.swing.JTextField tf_limite_compras;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_nome_fantasia;
    private javax.swing.JTextField tf_numero;
    private javax.swing.JTextField tf_porcentagem_desconto;
    private javax.swing.JTextField tf_razao_social;
    private javax.swing.JTextField tf_responsavel_compras;
    private javax.swing.JTextField tf_rg;
    private javax.swing.JTextField tf_rua;
    private javax.swing.JTextField tf_telefone1;
    private javax.swing.JTextField tf_telefone2;
    // End of variables declaration//GEN-END:variables

    public void lookandfeel() throws ClassNotFoundException {
        try {
            UIManager.setLookAndFeel(seta_look);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }
    
    public void gravarDados() {
            
                          
        //  Dados Empresa
        String nome              = tf_nome.getText();
        String data_nascimento   = tf_dataNascimento.getText();
        String rg                = tf_rg.getText();
        String cpf               = tf_cpf.getText();
        String cnpj              = tf_cnpj.getText();
        String nome_fantasia     = tf_nome_fantasia.getText();
        String razao_social      = tf_razao_social.getText();
        String inscricao_estadual = tf_inscricao_estadual.getText();
        
        //  Endereco e Contato
        String rua               = tf_rua.getText();
        String numero            = tf_numero.getText();
        String bairro            = tf_bairro.getText();
        String cidade            = tf_cidade.getText();
        String cep               = tf_cep.getText();
        String telefone1         = tf_telefone1.getText();
        String telefone2         = tf_telefone2.getText();
        String celular           = tf_celular.getText();
        String nextel            = tf_id_nextel.getText();
        String email             = tf_email.getText();
        
        //  Informacoes 
        String nome_responsavel  = tf_responsavel_compras.getText();
        String data_cadastro     = tf_data_cadastro.getText();
        String desconto          = tf_porcentagem_desconto.getText();
        String limite_compra     = tf_limite_compras.getText();
        String observacao        = ta_observacoes.getText();
        int ramo_id              = com_atividades.getSelectedIndex();

        String sql = "INSERT INTO cliente "
                + "(cli_nome, cli_data_nascimento, cli_rg, cli_cpf, cli_cnpj, cli_nome_fantasia, cli_razao_social, cli_inscricao_estadual, cli_rua, cli_numero, cli_bairro, cli_cidade, cli_cep, cli_telefone1, cli_telefone2, cli_celular, cli_id_nextel, cli_email, cli_nome_responsavel, cli_data_cadastro, cli_porcentagem_desconto, cli_limite_compra, cli_observacoes, fk_ram_id) VALUES "
                + "('"+nome+"','"+data_nascimento+"','"+rg+"','"+cpf+"','"+cnpj+"','"+nome_fantasia+"','"+razao_social+"','"+inscricao_estadual+"','"+rua+"','"+numero+"','"+bairro+"','"+cidade+"','"+cep+"','"+telefone1+"','"+telefone2+"','"+celular+"','"+nextel+"','"+email+"','"+nome_responsavel+"','"+data_cadastro+"','"+desconto+"','"+limite_compra+"','"+observacao+"','"+ramo_id+"')";
        
        database.updateBase(sql);
        
    }   
    
    public void limparCampos() {

        tf_nome.setText("");
        tf_dataNascimento.setText("");
        tf_rg.setText("");
        tf_cpf.setText("");
        tf_cnpj.setText("");
        tf_nome_fantasia.setText("");
        tf_razao_social.setText("");
        tf_inscricao_estadual.setText("");

        tf_rua.setText("");
        tf_numero.setText("");
        tf_bairro.setText("");
        tf_cidade.setText("Caraguatatuba");
        tf_cep.setText("");
        tf_telefone1.setText("");
        tf_telefone2.setText("");
        tf_celular.setText("");
        tf_id_nextel.setText("");
        tf_email.setText("");

        tf_responsavel_compras.setText("");
        tf_data_cadastro.setText("");
        tf_porcentagem_desconto.setText("");
        tf_limite_compras.setText("");
        ta_observacoes.setText("");
        com_atividades.setSelectedIndex(0);
        
        tf_nome.requestFocus();
    }
    
    void chamarInicial() {
        //Chama a home do sistema
        TelaInicial ti = new TelaInicial();
        ti.setVisible(true);
    }
   
    
    void chamarMesma() throws ClassNotFoundException, ParseException {
        //Chama a home do sistema
        CadastroCliente cli = new CadastroCliente();
        cli.setVisible(true);
    }
    
    void setarIcone() 
    {
        URL url = this.getClass().getResource("cubo_grande.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }
     
    void checarCamposObrigatorios() // Consulta se todos os campos obrigatórios foram inseridos corretamente.
    {
        String nome        = tf_nome.getText();
        String cpf         = tf_cpf.getText();
        String inscricao   = tf_inscricao_estadual.getText();
        String responsavel = tf_responsavel_compras.getText();
        
        if(nome == null || nome.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Preencha o campo Nome", "Invicta Code", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(cpf == null || cpf.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Preencha o campo CPF", "Invicta Code", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(inscricao == null || inscricao.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Preencha o campo Inscrição Estadual", "Invicta Code", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(responsavel == null || responsavel.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Preencha o campo Responsável pelas Compras", "Invicta Code", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            gravarDados();
        }
        
    }
    
    // Lista os clientes cadastrados ao inicializar a tela  
    void listarClientes () {
        String sql = "SELECT cli_id, cli_nome, cli_cnpj, cli_nome_fantasia, cli_cidade, cli_nome_responsavel FROM cliente";
        
        DefaultTableModel modelo = (DefaultTableModel) jt_cliente.getModel();
        modelo.setNumRows(0);

        
        try 
        {
            ResultSet resultado = database.consultaTable(sql);
            while (resultado.next()){
                modelo.addRow(new Object[]{
                    resultado.getInt("cli_id"), 
                    resultado.getString("cli_nome"), 
                    resultado.getString("cli_cnpj"), 
                    resultado.getString("cli_nome_fantasia"), 
                    resultado.getString("cli_cidade"),
                    resultado.getString("cli_nome_responsavel")
                });
            }
                resultado.first();
        } 
        catch (SQLException erro) 
        {
            JOptionPane.showMessageDialog(null, "Erro ao listar a tabela " + erro);
        }
    }
    
    // Limpa tabela antes de listar todos os clientes
    void limparClienteJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jt_cliente.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }
    
    void excluirCliente (int codigo){
        String sql = "DELETE FROM cliente WHERE cli_id = '"+codigo+"'";
        
        int opcao = JOptionPane.showConfirmDialog
        (null, "Deseja deletar este Cliente?", "Invicta Code", JOptionPane.INFORMATION_MESSAGE);
        if(opcao == 0)
        {
            database.updateBase(sql);
        }
    }
}
