package Gerenciamento;

import Auxiliar.ConsultaCalendario;
import Auxiliar.Sobre;
import Auxiliar.data;
import Cadastro.CadastroCliente;
import Cadastro.CadastroFornecedor;
import Cadastro.CadastroUsuario;
import Conexao.AcessoBD;
import Login.Sessao;
import Login.UsuarioLogado;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * @author Henrique Nunweiler Angelim Silva
 */
public final class TelaInicial extends javax.swing.JFrame {
    data mostra_data = new data();
    String seta_look = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
    AcessoBD db = new AcessoBD("japa");
    UsuarioLogado ul = new UsuarioLogado();
    
            
    public TelaInicial() {
        initComponents();
        aberturaSistema();
        setarIcone();       
        
    }
    
    public TelaInicial(String usuario) {//Esse construtor puxa o nome do usuário que está logado
        initComponents();
        aberturaSistema();
        setarIcone();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        la_logo = new javax.swing.JLabel();
        la_data = new javax.swing.JLabel();
        la_hora = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bo_atalho1 = new javax.swing.JButton();
        bo_atalho2 = new javax.swing.JButton();
        bo_usuario = new javax.swing.JButton();
        bo_cliente = new javax.swing.JButton();
        label_atalhos = new javax.swing.JLabel();
        bo_atalho3 = new javax.swing.JButton();
        bo_fornecedor = new javax.swing.JButton();
        la_usuario_texto = new javax.swing.JLabel();
        la_usuario = new javax.swing.JLabel();
        jmbPrincipal = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmi_cadastro_clientes = new javax.swing.JMenuItem();
        jmi_cadastro_fornecedores = new javax.swing.JMenuItem();
        jmi_cadastro_usuarios = new javax.swing.JMenuItem();
        jmConsulta = new javax.swing.JMenu();
        jmi_consulta_clientes = new javax.swing.JMenuItem();
        jmi_consulta_fornecedores = new javax.swing.JMenuItem();
        jmi_consulta_usuarios = new javax.swing.JMenuItem();
        jmRelatorio = new javax.swing.JMenu();
        jmi_relatório_clientes = new javax.swing.JMenuItem();
        jmi_relatório_fornecedores = new javax.swing.JMenuItem();
        jmi_relatório_usuarios = new javax.swing.JMenuItem();
        jmAuxiliar = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmSobre = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jmi_chamarSite = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Financeiro - Japa Auto Peças");
        setMinimumSize(new java.awt.Dimension(1024, 725));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        la_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/tela.png"))); // NOI18N
        la_logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                la_logoMouseClicked(evt);
            }
        });

        la_data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        la_data.setText("Data:");

        la_hora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        la_hora.setText("Hora:");

        jPanel1.setBackground(new java.awt.Color(6, 126, 204));

        bo_atalho1.setBackground(new java.awt.Color(255, 255, 255));
        bo_atalho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UserIcons/group.png"))); // NOI18N
        bo_atalho1.setText("Atalho A");
        bo_atalho1.setMaximumSize(new java.awt.Dimension(155, 25));
        bo_atalho1.setMinimumSize(new java.awt.Dimension(155, 25));
        bo_atalho1.setPreferredSize(new java.awt.Dimension(155, 25));
        bo_atalho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_atalho1ActionPerformed(evt);
            }
        });

        bo_atalho2.setBackground(new java.awt.Color(255, 255, 255));
        bo_atalho2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UserIcons/user.png"))); // NOI18N
        bo_atalho2.setText("Atalho B");
        bo_atalho2.setMaximumSize(new java.awt.Dimension(160, 25));
        bo_atalho2.setMinimumSize(new java.awt.Dimension(160, 25));
        bo_atalho2.setPreferredSize(new java.awt.Dimension(160, 25));
        bo_atalho2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_atalho2ActionPerformed(evt);
            }
        });

        bo_usuario.setBackground(new java.awt.Color(255, 255, 255));
        bo_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UserIcons/user_gray.png"))); // NOI18N
        bo_usuario.setText("Cadastro de Usuários");
        bo_usuario.setMaximumSize(new java.awt.Dimension(160, 25));
        bo_usuario.setMinimumSize(new java.awt.Dimension(160, 25));
        bo_usuario.setPreferredSize(new java.awt.Dimension(160, 25));
        bo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_usuarioActionPerformed(evt);
            }
        });

        bo_cliente.setBackground(new java.awt.Color(255, 255, 255));
        bo_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UserIcons/user.png"))); // NOI18N
        bo_cliente.setText("Cadastro de Clientes");
        bo_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_clienteActionPerformed(evt);
            }
        });

        label_atalhos.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        label_atalhos.setForeground(new java.awt.Color(255, 255, 255));
        label_atalhos.setText("Atalhos:");

        bo_atalho3.setBackground(new java.awt.Color(255, 255, 255));
        bo_atalho3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UserIcons/user_female.png"))); // NOI18N
        bo_atalho3.setText("Atalho C");
        bo_atalho3.setMaximumSize(new java.awt.Dimension(160, 25));
        bo_atalho3.setMinimumSize(new java.awt.Dimension(160, 25));
        bo_atalho3.setPreferredSize(new java.awt.Dimension(160, 25));
        bo_atalho3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_atalho3ActionPerformed(evt);
            }
        });

        bo_fornecedor.setBackground(new java.awt.Color(255, 255, 255));
        bo_fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UserIcons/user_green.png"))); // NOI18N
        bo_fornecedor.setText("Cadastro de Fornecedores");
        bo_fornecedor.setMaximumSize(new java.awt.Dimension(160, 25));
        bo_fornecedor.setMinimumSize(new java.awt.Dimension(160, 25));
        bo_fornecedor.setPreferredSize(new java.awt.Dimension(160, 25));
        bo_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo_fornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bo_atalho1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bo_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bo_atalho2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bo_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(bo_atalho3, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                    .addComponent(label_atalhos))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(label_atalhos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bo_atalho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bo_atalho2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bo_atalho3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bo_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bo_cliente))
                .addContainerGap())
        );

        la_usuario_texto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        la_usuario_texto.setText("Usuário: ");

        la_usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        la_usuario.setText("...");

        jmCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/disk.png"))); // NOI18N
        jmCadastro.setText("Cadastro");
        jmCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroActionPerformed(evt);
            }
        });

        jmi_cadastro_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UserIcons/user.png"))); // NOI18N
        jmi_cadastro_clientes.setText("Cadastro de Clientes");
        jmi_cadastro_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cadastro_clientesActionPerformed(evt);
            }
        });
        jmCadastro.add(jmi_cadastro_clientes);

        jmi_cadastro_fornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UserIcons/user_green.png"))); // NOI18N
        jmi_cadastro_fornecedores.setText("Cadastro de Fornecedores");
        jmi_cadastro_fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cadastro_fornecedoresActionPerformed(evt);
            }
        });
        jmCadastro.add(jmi_cadastro_fornecedores);

        jmi_cadastro_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UserIcons/user_gray.png"))); // NOI18N
        jmi_cadastro_usuarios.setText("Cadastro de Usuários");
        jmi_cadastro_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cadastro_usuariosActionPerformed(evt);
            }
        });
        jmCadastro.add(jmi_cadastro_usuarios);

        jmbPrincipal.add(jmCadastro);

        jmConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/SearchIcons/magnifier.png"))); // NOI18N
        jmConsulta.setText("Consultas");
        jmConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaActionPerformed(evt);
            }
        });

        jmi_consulta_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UserIcons/user.png"))); // NOI18N
        jmi_consulta_clientes.setText("Consulta de Clientes");
        jmi_consulta_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_consulta_clientesActionPerformed(evt);
            }
        });
        jmConsulta.add(jmi_consulta_clientes);

        jmi_consulta_fornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UserIcons/user_green.png"))); // NOI18N
        jmi_consulta_fornecedores.setText("Consulta de Fornecedores");
        jmi_consulta_fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_consulta_fornecedoresActionPerformed(evt);
            }
        });
        jmConsulta.add(jmi_consulta_fornecedores);

        jmi_consulta_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UserIcons/user_gray.png"))); // NOI18N
        jmi_consulta_usuarios.setText("Consulta de Usuários");
        jmi_consulta_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_consulta_usuariosActionPerformed(evt);
            }
        });
        jmConsulta.add(jmi_consulta_usuarios);

        jmbPrincipal.add(jmConsulta);

        jmRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/ReportIcons/printer.png"))); // NOI18N
        jmRelatorio.setText("Relatórios");
        jmRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRelatorioActionPerformed(evt);
            }
        });

        jmi_relatório_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UserIcons/user.png"))); // NOI18N
        jmi_relatório_clientes.setText("Relatório de Clientes");
        jmi_relatório_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_relatório_clientesActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmi_relatório_clientes);

        jmi_relatório_fornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UserIcons/user_green.png"))); // NOI18N
        jmi_relatório_fornecedores.setText("Relatório de Fornecedores");
        jmi_relatório_fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_relatório_fornecedoresActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmi_relatório_fornecedores);

        jmi_relatório_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UserIcons/user_gray.png"))); // NOI18N
        jmi_relatório_usuarios.setText("Relatório de Usuários");
        jmi_relatório_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_relatório_usuariosActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmi_relatório_usuarios);

        jmbPrincipal.add(jmRelatorio);

        jmAuxiliar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/TimeIcons/time.png"))); // NOI18N
        jmAuxiliar.setText("Auxiliar");
        jmAuxiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAuxiliarActionPerformed(evt);
            }
        });

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/CalendarIcons/date.png"))); // NOI18N
        jMenuItem2.setText("Calendário");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmAuxiliar.add(jMenuItem2);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/money_dollar.png"))); // NOI18N
        jMenuItem5.setText("Calculadora");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmAuxiliar.add(jMenuItem5);

        jmbPrincipal.add(jmAuxiliar);

        jmSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/cubo.png"))); // NOI18N
        jmSobre.setText("Sobre");

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/cubo.png"))); // NOI18N
        jMenuItem15.setText("Sobre o Gerenciador Financeiro");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jmSobre.add(jMenuItem15);

        jmi_chamarSite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/UpdateIcons/world.png"))); // NOI18N
        jmi_chamarSite.setText("Site Invicta Code");
        jmi_chamarSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_chamarSiteActionPerformed(evt);
            }
        });
        jmSobre.add(jmi_chamarSite);

        jmbPrincipal.add(jmSobre);

        setJMenuBar(jmbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(la_hora)
                            .addComponent(la_data)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(la_usuario_texto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(la_usuario)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(la_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(la_logo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(la_data)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(la_hora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_usuario_texto)
                            .addComponent(la_usuario))))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(830, 557));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_cadastro_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cadastro_clientesActionPerformed
        try {
            chamarCliente();
            dispose();
        } catch (ClassNotFoundException | ParseException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmi_cadastro_clientesActionPerformed

    private void jmi_cadastro_fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cadastro_fornecedoresActionPerformed
        try {
                chamarTelaFornecedor();
                dispose();
            } catch (ClassNotFoundException | ParseException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jmi_cadastro_fornecedoresActionPerformed

    private void jmi_cadastro_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cadastro_usuariosActionPerformed
        chamarUsuario();
    }//GEN-LAST:event_jmi_cadastro_usuariosActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        mostra_data.le_hora();
        la_hora.setText("Hora Atual: "+mostra_data.getHora());
    }//GEN-LAST:event_timer1OnTime

    private void bo_atalho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_atalho1ActionPerformed

    }//GEN-LAST:event_bo_atalho1ActionPerformed

    private void bo_atalho2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_atalho2ActionPerformed
        chamarUsuario();
    }//GEN-LAST:event_bo_atalho2ActionPerformed

    private void bo_atalho3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_atalho3ActionPerformed
        chamarDefinirCacamba();
    }//GEN-LAST:event_bo_atalho3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fecharTela();
    }//GEN-LAST:event_formWindowClosing

    private void bo_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_fornecedorActionPerformed
        try {
                chamarTelaFornecedor();
                dispose();
            } catch (ClassNotFoundException | ParseException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_bo_fornecedorActionPerformed

    private void la_logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_la_logoMouseClicked
        chamarSite();
    }//GEN-LAST:event_la_logoMouseClicked

    private void bo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_usuarioActionPerformed
            try {
                chamarTelaUsuario();
                dispose();
            } catch (ClassNotFoundException | ParseException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_bo_usuarioActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        db.finalizaBD();
    }//GEN-LAST:event_formWindowClosed

    private void bo_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo_clienteActionPerformed
        try {
            chamarCliente();
            dispose();
        } catch (ClassNotFoundException | ParseException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bo_clienteActionPerformed

    private void jmi_chamarSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_chamarSiteActionPerformed
        Desktop desktop = Desktop.getDesktop();  
        try {  
                   URI uri = new URI("www.invictacode.com.br");  
                   desktop.browse(uri);  
        }  
        catch(IOException | URISyntaxException ioe) {  
        }  
    }//GEN-LAST:event_jmi_chamarSiteActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        Sobre so = new Sobre();
        so.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jmCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroActionPerformed
            try {
                chamarTelaUsuario();
            } catch (ClassNotFoundException | ParseException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jmCadastroActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ConsultaCalendario cc = new ConsultaCalendario();
        cc.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmAuxiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAuxiliarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmAuxiliarActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try 
        {  
            Runtime.getRuntime().exec("calc");  
        }  
        catch (IOException exc) {  
            exc.printStackTrace();  
        }  
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jmi_consulta_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_consulta_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_consulta_clientesActionPerformed

    private void jmi_consulta_fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_consulta_fornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_consulta_fornecedoresActionPerformed

    private void jmi_consulta_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_consulta_usuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_consulta_usuariosActionPerformed

    private void jmConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmConsultaActionPerformed

    private void jmi_relatório_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_relatório_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_relatório_clientesActionPerformed

    private void jmi_relatório_fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_relatório_fornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_relatório_fornecedoresActionPerformed

    private void jmi_relatório_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_relatório_usuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_relatório_usuariosActionPerformed

    private void jmRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bo_atalho1;
    private javax.swing.JButton bo_atalho2;
    private javax.swing.JButton bo_atalho3;
    private javax.swing.JButton bo_cliente;
    private javax.swing.JButton bo_fornecedor;
    private javax.swing.JButton bo_usuario;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmAuxiliar;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmConsulta;
    private javax.swing.JMenu jmRelatorio;
    private javax.swing.JMenu jmSobre;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JMenuItem jmi_cadastro_clientes;
    private javax.swing.JMenuItem jmi_cadastro_fornecedores;
    private javax.swing.JMenuItem jmi_cadastro_usuarios;
    private javax.swing.JMenuItem jmi_chamarSite;
    private javax.swing.JMenuItem jmi_consulta_clientes;
    private javax.swing.JMenuItem jmi_consulta_fornecedores;
    private javax.swing.JMenuItem jmi_consulta_usuarios;
    private javax.swing.JMenuItem jmi_relatório_clientes;
    private javax.swing.JMenuItem jmi_relatório_fornecedores;
    private javax.swing.JMenuItem jmi_relatório_usuarios;
    private javax.swing.JLabel la_data;
    private javax.swing.JLabel la_hora;
    private javax.swing.JLabel la_logo;
    private javax.swing.JLabel la_usuario;
    private javax.swing.JLabel la_usuario_texto;
    private javax.swing.JLabel label_atalhos;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
    public void lookandfeel()
    {
            try
            {
            UIManager.setLookAndFeel(seta_look);
            SwingUtilities.updateComponentTreeUI(this);
            }
            catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException erro)
            {
            JOptionPane.showMessageDialog(null, erro);
            }
    }
  
    void chamarCliente() throws ClassNotFoundException, ParseException {
        CadastroCliente cc = new CadastroCliente();
        cc.setVisible(true);
        dispose();
    }
    
    void chamarTelaUsuario() throws ClassNotFoundException, ParseException {
        CadastroUsuario cu = new CadastroUsuario();
        cu.setVisible(true);
    }
    
    void chamarTelaFornecedor() throws ClassNotFoundException, ParseException {
        CadastroFornecedor cf = new CadastroFornecedor();
        cf.setVisible(true);
    }
    
    void chamarUsuario()
    {
        String usuario = la_usuario.getText();
        
        int codigo = 3;
        try 
        {
            ResultSet resultado = db.consultaTable("SELECT usu_acesso FROM usuario WHERE usu_usuario = '"+usuario+"'");
            while (resultado.next()) //Aqui você adiciona os campos do banco de dados no jTable.
            {
                //System.out.println(resultado.getInt("ano"));
                codigo = resultado.getInt("usu_acesso");
            }
                resultado.first();
        } 
        catch (SQLException erro) 
        {
            JOptionPane.showMessageDialog(null, "Erro ao listar a tabela " + erro);
        }
        
        if(codigo == 0)
        {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar essa opção."
                    + "\nFavor, entrar em contato com o seu gerente.", "Invicta Code", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(codigo == 1)
        {
            CadastroUsuario cu = new CadastroUsuario();
            cu.setVisible(true);
            dispose();
            
        }else{
            JOptionPane.showMessageDialog(null, "Erro na requisição.\nEntre em contato com a equipe técnica"
                    + "\nda Invicta Code para sanar o problema.\nErro 001: código de retorno: " + codigo, "Invicta Code", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    /*
        void chamarUsuario()
    {
        Transacao tr = new Transacao();
        tr.setVisible(true);
        dispose();
    }
    */
     void chamarSite()
        {
            Desktop desktop;  
            desktop = Desktop.getDesktop();  
            URI uri;  
            try {  
                       uri = new URI("http://www.invictacode.com.br/software");  
                       desktop.browse(uri);  
            }  
            catch(IOException | URISyntaxException ioe) {  
            }
    
}

    void fecharTela() {
        int opcao = JOptionPane.showConfirmDialog
        (null, "Deseja sair do cadastro?", "Invicta Code", JOptionPane.INFORMATION_MESSAGE);
        if(opcao == 0)
        {
            System.exit(0);
        }
        else
        {
            chamarMesma();
        }
    
    }

    void chamarMesma() {
        TelaInicial ti = new TelaInicial();
        ti.setVisible(true);
    }

    void chamarDefinirCacamba() {
        String usuario = la_usuario.getText();
        
        int codigo = 3;
        try 
        {
            ResultSet resultado = db.consultaTable("SELECT usu_acesso FROM usuario WHERE usu_usuario = '"+usuario+"'");
            while (resultado.next()) //Aqui você adiciona os campos do banco de dados no jTable.
            {
                //System.out.println(resultado.getInt("ano"));
                codigo = resultado.getInt("usu_acesso");
            }
                resultado.first();
        } 
        catch (SQLException erro) 
        {
            JOptionPane.showMessageDialog(null, "Erro ao listar a tabela " + erro);
        }
        
        if(codigo == 0)
        {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar essa opção."
                    + "\nFavor, entrar em contato com o seu gerente.", "Invicta Code", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(codigo == 1)
        {
           /* ValorCacamba dc = new ValorCacamba(usuario);
            dc.setVisible(true);
            dispose();*/
        }else{
            JOptionPane.showMessageDialog(null, "Erro na requisição.\nEntre em contato com a equipe técnica"
                    + "\nda Invicta Code para sanar o problema.\nErro 001: código de retorno: " + codigo, "Invicta Code", JOptionPane.INFORMATION_MESSAGE);
        }
                
    }

  
    
    void aberturaSistema()
    {
        setLocationRelativeTo(null);
        lookandfeel();
        
        la_usuario.setText(Sessao.getInstance().getUsuario());
        mostra_data.le_data();
       
        la_data.setText(""+mostra_data.getDia_semana()+", dia "+mostra_data.getDia()+" de "+mostra_data.getMes()+" de "+mostra_data.getAno());
        mostra_data.le_hora();
        la_hora.setText("Hora Atual: "+mostra_data.getHora());
        
        timer1.start(); 
    }
    
    void setarIcone()
    {
        URL url = this.getClass().getResource("cubo_grande.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }
    
 
  
}

